#ifndef __YAFFS_CONFIG_H__
#define __YAFFS_CONFIG_H__

#ifdef KBUILD_MODNAME
#define CONFIG_YAFFS_FS
#define CONFIG_YAFFS_YAFFS1
#define CONFIG_YAFFS_YAFFS2
#define CONFIG_YAFFS_DOES_ECC
#define CONFIG_YAFFS_ECC_WRONG_ORDER
#define CONFIG_YAFFS_DISABLE_CHUNK_ERASED_CHECK
#define CONFIG_YAFFS_SHORT_NAMES_IN_RAM
#endif /* KBUILD_MODNAME */

#endif /* __YAFFS_CONFIG_H__ */
