#!/bin/bash

TREE_BASE=/mnt/dirtree

for (( f=0; f<500; f++ ))
do
	for (( d=0; d<10; d++ ))
	do
		mkdir -p $TREE_BASE/dir$d
		dd bs=1024 count=5 if=/dev/zero of=$TREE_BASE/dir$d/file$f
	done
done


echo "Foo bar file" > $TREE_BASE/foo_file

ln $TREE_BASE/foo_file $TREE_BASE/../foo_link





